# Generated by Django 4.2.11 on 2024-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='', max_length=3)),
                ('Sex', models.CharField(default='', max_length=2)),
                ('Standard', models.IntegerField(default='', max_length=3)),
                ('Percentage', models.FloatField(default='', max_length=4)),
                ('Address', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
