# Generated by Django 4.2.11 on 2024-08-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Percentage',
            field=models.FloatField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Standard',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
