# Generated by Django 4.2.11 on 2024-08-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_alter_datas_age_alter_datas_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Standard',
            field=models.IntegerField(),
        ),
    ]
