# Generated by Django 4.2.11 on 2024-08-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_alter_datas_age_alter_datas_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Standard',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
